### ISSUE TITLE
Description en anglais

### ISSUE THREAD

**Issue by rcanet** [seeme00/translation-motw-fr#1]
Bonjour, 
je pense que le soucis ne vient pas d'une erreur de manipe (nouveau à FoundryVTT). Mais les description de tous les compendium sont en anglais sur Foundry (alors que tes fichiers json sont bien en français). Je me disais que peut-être le mapping avait changé mais même en cherchant, je n'ai pas réussi à résoudre ce petit soucis. Est-ce que tu aurais une idée ?
Bonne journée (et super boulot pour cette traduction !)

**Comment by seeme00** [comment]
Bonsoir,
Je viens de faire une MAJ de fvtt, je n'ai pas pu observer ton problème.
Quelle version de foundry utilises-tu?
Est-ce que les modules sont bien installés et actifs?

Le minimum:
![image](https://user-images.githubusercontent.com/11278696/189213223-c8e2d98e-b848-4065-8f00-c875ca8e0011.png)

Merci,
Julien N.

**Comment by rcanet** [comment]
Bonsoir, 
Merci pour la réponse rapide déjà ! Oui tout est bien chargé (cf image ci-jointe). Ma version est la version 10 Build 284

Rémy C. 
![image](https://user-images.githubusercontent.com/38335075/189218458-f4192dd2-8220-4b1b-a6c4-cb98ba814462.png)

**Comment by seeme00** [comment]
J'ai la repro :)
Je vais regarder ça, merci.

**Comment by seeme00** [comment]
Fixé dans la 1.2, merci :)

**Comment by rcanet** [comment]
Ca marche du feu de dieu, merci beaucoup pour le fix !
